-- SQL скрипт для вставки моковых данных игроков
-- Используйте этот скрипт для ручного добавления данных в таблицу players

INSERT INTO players (
  "fullName",
  "dateOfBirth",
  "transfermarktLink",
  "photoUrl",
  country,
  city,
  league,
  club,
  "youthAcademy",
  "mainPosition",
  "position2",
  "position3",
  height,
  weight,
  foot,
  "contractExpires",
  "currentLevel",
  potential,
  shortlist,
  "createdAt",
  "updatedAt"
) VALUES
-- Lionel Messi
(
  'Lionel Messi',
  '1987-06-24',
  'https://www.transfermarkt.com/lionel-messi/profil/spieler/28003',
  'https://example.com/messi.jpg',
  'Argentina',
  'Rosario',
  'Major League Soccer',
  'Inter Miami',
  'Newell''s Old Boys',
  'forward',
  'winger',
  'midfielder',
  170,
  72,
  'left',
  '2025-12-31',
  9,
  9,
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
-- Kylian Mbappé
(
  'Kylian Mbappé',
  '1998-12-20',
  'https://www.transfermarkt.com/kylian-mbappe/profil/spieler/342229',
  'https://example.com/mbappe.jpg',
  'France',
  'Paris',
  'Ligue 1',
  'Paris Saint-Germain',
  'AS Bondy',
  'striker',
  'forward',
  'winger',
  178,
  73,
  'right',
  '2024-06-30',
  9,
  10,
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
-- Virgil van Dijk
(
  'Virgil van Dijk',
  '1991-07-08',
  'https://www.transfermarkt.com/virgil-van-dijk/profil/spieler/139590',
  'https://example.com/vandijk.jpg',
  'Netherlands',
  'Breda',
  'Premier League',
  'Liverpool',
  'Willem II',
  'defender',
  NULL,
  NULL,
  193,
  92,
  'right',
  '2025-06-30',
  8,
  8,
  false,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
-- Kevin De Bruyne
(
  'Kevin De Bruyne',
  '1991-06-28',
  'https://www.transfermarkt.com/kevin-de-bruyne/profil/spieler/88755',
  'https://example.com/debruyne.jpg',
  'Belgium',
  'Drongen',
  'Premier League',
  'Manchester City',
  'KRC Genk',
  'midfielder',
  'forward',
  NULL,
  181,
  70,
  'right',
  '2025-06-30',
  9,
  9,
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
-- Alisson Becker
(
  'Alisson Becker',
  '1992-10-02',
  'https://www.transfermarkt.com/alisson/profil/spieler/121895',
  'https://example.com/alisson.jpg',
  'Brazil',
  'Novo Hamburgo',
  'Premier League',
  'Liverpool',
  'Internacional',
  'goalkeeper',
  NULL,
  NULL,
  191,
  91,
  'right',
  '2027-06-30',
  9,
  9,
  false,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);
